/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Shungite(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/Shungite.glb');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.model_Material_u1_v1}
        geometry={nodes.model.geometry}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload('/models/Shungite.glb');
