/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import PropTypes from 'prop-types';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useHandleAnimation } from './useHandleAnimation';

export default function Model({ thinking, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf',
  );
  const { actions } = useAnimations(animations, group);
  useHandleAnimation(actions, thinking);

  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group scale={[0.6, 0.6, 0.6]}>
        <primitive object={nodes.root} />
        <skinnedMesh
          geometry={nodes.Vieux.geometry}
          material={materials['color_main.001']}
          skeleton={nodes.Vieux.skeleton}
        />
      </group>
    </group>
  );
}

Model.propTypes = {
  thinking: PropTypes.bool,
};

Model.defaultProps = {
  thinking: false,
};

useGLTF.preload(
  'https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/old-korrigan/model.gltf',
);
