/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useMemo, useEffect } from 'react';
import PropTypes from 'prop-types';
import { useGraph } from '@react-three/fiber';
import { useGLTF, useAnimations } from '@react-three/drei';
import { SkeletonUtils } from 'three/examples/jsm/utils/SkeletonUtils';

import Hat from './Hat';
import { useHandleAnimation } from './useHandleAnimation';

const AnimationHandler = ({ model, fwdRef, moving, jumping }) => {
  const animations = model ? model.animations : null;
  const { actions, mixer } = useAnimations(animations, fwdRef);
  useHandleAnimation(actions, mixer, moving, jumping);

  return null;
};

export default function Model({ moving, jumping, hat, scale, ...props }) {
  const group = useRef(null);
  const hatRef = useRef(null);

  const { scene, animations } = useGLTF('/models/BigNose.glb');
  const copiedScene = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes } = useGraph(copiedScene);

  const model = useMemo(() => ({ animations }), [animations]);

  useEffect(() => {
    if (!nodes || !nodes.Character1_Hips) return;
    if (!hat || !hatRef.current) return;
    nodes.Character1_Hips.traverse(obj => {
      if (obj.name === 'Character1_Head') {
        obj.add(hatRef.current);
      }
    });
  }, [hat, nodes]);

  return (
    <>
      <AnimationHandler model={model} fwdRef={group} moving={moving} jumping={jumping} />
      {/* eslint-disable-next-line react/jsx-props-no-spreading */}
      <group {...props} dispose={null}>
        <Hat type={hat} ref={hatRef} />
        <group
          name="BigNose"
          position={[-0.02, -0.02, 0.03]}
          // rotation={[1.53, -0.05, -0.14]}
          rotation={[1.53, -0.05, -0.14]}
          // scale={[0.0135, 0.0135, 0.0125]}
          scale={[0.0135 * scale[0], 0.0135 * scale[1], 0.015 * scale[2]]}
          ref={group}
        >
          <primitive object={nodes.Character1_Hips} />
          <skinnedMesh
            geometry={nodes.body_NPC.geometry}
            material={nodes.body_NPC.material}
            skeleton={nodes.body_NPC.skeleton}
          />
          <skinnedMesh
            geometry={nodes.head_neutral_NPC.geometry}
            material={nodes.head_neutral_NPC.material}
            skeleton={nodes.head_neutral_NPC.skeleton}
          />
        </group>
      </group>
    </>
  );
}

Model.propTypes = {
  /* eslint-disable react/forbid-prop-types */
  moving: PropTypes.bool,
  jumping: PropTypes.bool,
  hat: PropTypes.string,
  scale: PropTypes.array,
  /* eslint-enable react/forbid-prop-types */
};

Model.defaultProps = {
  moving: false,
  jumping: false,
  hat: null,
  scale: [1, 1, 1],
};

useGLTF.preload('/models/BigNose.glb');
