/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/ShipWreck/ship_wreck.gltf');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0, 0]}>
        <mesh
          material={materials.wood}
          geometry={nodes.ship_wreck_8angles_1.geometry}
          castShadow
          receiveShadow
        />
        <mesh
          material={materials.iron}
          geometry={nodes.ship_wreck_8angles_2.geometry}
          castShadow
          receiveShadow
        />
        <mesh
          material={materials.woodDark}
          geometry={nodes.ship_wreck_8angles_3.geometry}
          castShadow
          receiveShadow
        />
        <mesh
          material={materials.window}
          geometry={nodes.ship_wreck_8angles_4.geometry}
          castShadow
          receiveShadow
        />
        <mesh
          material={materials.leaves}
          geometry={nodes.ship_wreck_8angles_5.geometry}
          castShadow
          receiveShadow
        />
        {/* eslint-disable no-underscore-dangle */}
        <mesh
          material={materials._defaultMat}
          geometry={nodes.ship_wreck_8angles_6.geometry}
          castShadow
          receiveShadow
        />
        {/* eslint-enable no-underscore-dangle */}
      </group>
    </group>
  );
}

useGLTF.preload('/models/ShipWreck/ship_wreck.gltf');
