/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/donut-sprinkles/model.gltf',
  );
  useEffect(() => {
    if (!materials) return;
    Object.values(materials).forEach(material => {
      // eslint-disable-next-line no-param-reassign
      material.metalness = 0;
    });
  }, [materials]);
  //   scene.traverse(obj => {
  //     if (obj.isMesh) obj.geometry.computeVertexNormals();
  //   });
  // }, [nodes, scene]);
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_donutSprinkles.geometry} material={materials.brownLight} />
      <mesh geometry={nodes.Mesh_donutSprinkles_1.geometry} material={materials.purpleLight} />
      <mesh geometry={nodes.Mesh_donutSprinkles_2.geometry} material={materials.orange} />
      <mesh geometry={nodes.Mesh_donutSprinkles_3.geometry} material={materials.yellow} />
      <mesh geometry={nodes.Mesh_donutSprinkles_4.geometry} material={materials.green} />
    </group>
  );
}

useGLTF.preload(
  'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/donut-sprinkles/model.gltf',
);
