/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, animations } = useGLTF('/models/Campfire.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (!actions) return;
    // actions['CampFire.Light'].play();
    actions['NLA.Campfire.Twist'].play();
    // These two tracks don't work in 3, likely because they rely on mesh deformation
    // actions['NLA.Campfire.Jitter.XY'].play();
    // actions['NLA.Campfire.Jitter.Z'].play();
    // actions['NLA.Campfire.Lamp.Jitter.Z'].play();
    actions['NLA.Ember.000'].play();
    actions['NLA.Ember.001'].play();
    actions['NLA.Ember.002'].play();
    actions['NLA.Ember.003'].play();
    actions['NLA.Ember.004'].play();
    actions['NLA.Ember.005'].play();
    actions['NLA.Ember.006'].play();
    actions['NLA.Ember.007'].play();
  }, [actions]);
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group name="CampFireGRP">
        <group position={[0, -0.16, 0]}>
          <primitive object={nodes.BoneFireLower} />
          <group name="Flame">
            <skinnedMesh
              geometry={nodes.Cube001.geometry}
              material={nodes.Cube001.material}
              skeleton={nodes.Cube001.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Cube001_1.geometry}
              material={nodes.Cube001_1.material}
              skeleton={nodes.Cube001_1.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Cube001_2.geometry}
              material={nodes.Cube001_2.material}
              skeleton={nodes.Cube001_2.skeleton}
            />
            <skinnedMesh
              geometry={nodes.Cube001_3.geometry}
              material={nodes.Cube001_3.material}
              skeleton={nodes.Cube001_3.skeleton}
            />
          </group>
        </group>
        <mesh
          name="Ember007"
          geometry={nodes.Ember007.geometry}
          material={nodes.Ember007.material}
          position={[-1.27, 8.86, 0.5]}
          rotation={[Math.PI, -Math.PI / 5, Math.PI]}
          scale={[0.66, 0.66, 0.66]}
        />
        <mesh
          name="Ember006"
          geometry={nodes.Ember006.geometry}
          material={nodes.Ember006.material}
          position={[0.11, 7.07, 0.09]}
          rotation={[0, 1.52, 0]}
        />
        <mesh
          name="Ember005"
          geometry={nodes.Ember005.geometry}
          material={nodes.Ember005.material}
          position={[1.36, 8.31, 0.95]}
          rotation={[-Math.PI, 1.48, -Math.PI]}
        />
        <mesh
          name="Ember004"
          geometry={nodes.Ember004.geometry}
          material={nodes.Ember004.material}
          position={[0.24, 4.24, 0.28]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
        />
        <mesh
          name="Ember003"
          geometry={nodes.Ember003.geometry}
          material={nodes.Ember003.material}
          position={[-0.79, 3.56, 0.17]}
          scale={[0, 0, 0]}
        />
        <mesh
          name="Ember002"
          geometry={nodes.Ember002.geometry}
          material={nodes.Ember002.material}
          position={[-0.29, 6.42, 0.2]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.79, 0.79, 0.79]}
        />
        <mesh
          name="Ember000"
          geometry={nodes.Ember000.geometry}
          material={nodes.Ember000.material}
          position={[0, 6.6, 0]}
          rotation={[-Math.PI, Math.PI / 3, -Math.PI]}
          scale={[0.23, 0.23, 0.23]}
        />
        <mesh
          name="Ember001"
          geometry={nodes.Ember001.geometry}
          material={nodes.Ember001.material}
          position={[0.84, 7.29, 0.33]}
          rotation={[Math.PI, -Math.PI / 3, Math.PI]}
          scale={[0.17, 0.17, 0.17]}
        />
        <mesh
          geometry={nodes.Ember008.geometry}
          material={nodes.Ember008.material}
          position={[0.99, 6.46, 1.1]}
          rotation={[0, -1.01, 0]}
        />
      </group>
      <mesh geometry={nodes.LogB.geometry} material={nodes.LogB.material} />
      <mesh geometry={nodes.LogA.geometry} material={nodes.LogA.material} />
      {/* <mesh
        geometry={nodes.BoneShapeFireCircle.geometry}
        material={nodes.BoneShapeFireCircle.material}
        scale={[2.72, 2.72, 2.72]}
      /> */}
    </group>
  );
}

useGLTF.preload('/models/Campfire.glb');
