/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/StoneFormation/formationLarge_stone.gltf');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials.stone}
        geometry={nodes.formationLarge_stone_1.geometry}
        position={[0.8, 0, -0.4]}
        castShadow
      />
    </group>
  );
}

useGLTF.preload('/models/StoneFormation/formationLarge_stone.gltf');
