/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react';
import PropTypes from 'prop-types';
import { useGLTF } from '@react-three/drei';

const Model = React.forwardRef(({ position = [0, 0, 0], ...props }, ref) => {
  const { nodes } = useGLTF('/models/StoneFormation/formationLarge_stone.gltf');
  return (
    <mesh
      geometry={nodes.formationLarge_stone_1.geometry}
      castShadow
      position={[0.8 + position[0], position[1], -0.4 + position[2]]}
      // eslint-disable-next-line react/jsx-props-no-spreading
      {...props}
      dispose={null}
      ref={ref}
    />
  );
});

Model.propTypes = {
  // eslint-disable-next-line react/forbid-prop-types
  position: PropTypes.array,
};

Model.defaultProps = {
  position: [0, 0, 0],
};

export default Model;

useGLTF.preload('/models/StoneFormation/formationLarge_stone.gltf');
