/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/PalmShort/palm_detailed_short.gltf');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group position={[0.1, 0, -0.2]}>
        <mesh
          material={materials.wood}
          geometry={nodes.Group_18.geometry}
          scale={[0.77, 0.58, 0.77]}
          castShadow
        />
        <mesh
          material={materials.leaves}
          geometry={nodes.Group_20.geometry}
          position={[0.65, 1.28, -0.59]}
          castShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload('/models/PalmShort/palm_detailed_short.gltf');
