/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import { useGLTF } from '@react-three/drei';

export default function Model({ scale, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/burger/model.gltf',
  );
  useEffect(() => {
    if (!materials) return;
    Object.values(materials).forEach(material => {
      // eslint-disable-next-line no-param-reassign
      material.metalness = 0.25;
    });
  }, [materials]);
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} scale={scale * 4} {...props} dispose={null}>
      <mesh geometry={nodes.cheese.geometry} material={materials.yellow} position={[0, 0.09, 0]} />
      <mesh
        geometry={nodes.salad.geometry}
        material={materials.green}
        position={[0, 0.04, 0]}
        scale={[0.92, 0.75, 0.92]}
      />
      <mesh geometry={nodes.bunBottom.geometry} material={nodes.bunBottom.material} />
      <group position={[0, 0.14, 0]} scale={[1.56, 0.7, 1.56]}>
        {/* eslint-disable-next-line no-underscore-dangle */}
        <mesh geometry={nodes.Mesh_tomato.geometry} material={materials._defaultMat} />
        <mesh geometry={nodes.Mesh_tomato_1.geometry} material={materials.red} />
      </group>
      <mesh
        geometry={nodes.bunTop.geometry}
        material={nodes.bunTop.material}
        position={[0, 0.17, 0]}
      />
      <mesh
        geometry={nodes.patty.geometry}
        material={materials.brownDark}
        position={[0, 0.07, 0]}
      />
    </group>
  );
}

Model.propTypes = {
  scale: PropTypes.number,
};

Model.defaultProps = {
  scale: 1,
};

useGLTF.preload(
  'https://market-assets.fra1.cdn.digitaloceanspaces.com/market-assets/models/burger/model.gltf',
);
