/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import PropTypes from 'prop-types';
import { useGLTF } from '@react-three/drei';
import { degToRad } from '../../../utils/angles';

export default function Model({ innerRef, ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/BeachBall/beach_ball_edited.glb');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.2, 0]} rotation={[0, degToRad(-45), 0]}>
        <mesh
          geometry={nodes['node_MeshObject-1695992832-PolyPaper21'].geometry}
          material={materials.BlocksPaper}
          ref={innerRef}
          castShadow
        />
      </group>
    </group>
  );
}

Model.propTypes = {
  /* eslint-disable react/forbid-prop-types */
  innerRef: PropTypes.object,
  /* eslint-enable react/forbid-prop-types */
};

Model.defaultProps = {
  innerRef: null,
};

useGLTF.preload('/models/BeachBall/beach_ball_edited.glb');
