/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { degToRad } from '../../../utils/angles';

export default function Model(props) {
  const group = useRef();
  const { scene } = useGLTF('/models/Boombox2/model.gltf');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <primitive
        object={scene}
        scale={1.5}
        position={[-1.5, -2, 0]}
        rotation={[0, 0, degToRad(-7)]}
      />
    </group>
  );
}

useGLTF.preload('/models/Boombox2/model.gltf');
