/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/models/Boombox.glb');
  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    <group ref={group} {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials.lambert2} geometry={nodes.Mesh.geometry} />
        <mesh material={materials.lambert3} geometry={nodes.Mesh_1.geometry} />
      </group>
    </group>
  );
}

useGLTF.preload('/models/Boombox.glb');
